import 'dotenv/config';
import moment = require('moment');

export enum ColorEnums {
  base = '#FF7518',
  win = '#F6B132',
  normWin = '#ffffff',
  barelyWin = '#01AC20',
  notReallyWin = '#43B7DF',
  loss = '#C75D64',
  totalLoss = '#844D99',
  dead = '#B30000',
}

export const PAGE_LIMIT = 10;
export const DEFAULT_PAGE = 1;

export const randomChance = (min: number, max: number) => {
  return {
    min,
    number: Math.floor(Math.random() * (max - min + 1) + min),
    max,
  };
};

const falseStatusSet = new Set([
  'Admired',
  'Alive',
  'Appreciated',
  'Assured',
  'Cheerful',
  'Confident',
  'Content',
  'Delighted',
  'Determined',
  'Ecstatic',
  'Elated',
  'Encouraged',
  'Energized',
  'Enthusiastic',
  'Excited',
  'Exuberant',
  'Flattered',
  'Fortunate',
  'Fulfilled',
  'Glad',
  'Good',
  'Grateful',
  'Gratified',
  'Hopeful',
  'Joyful',
  'Alienated',
  'Ashamed',
  'Burdened',
  'Condemned',
  'Crushed',
  'Defeated',
  'Dejected',
  'Demoralized',
  'Depressed',
  'Deserted',
  'Despised',
  'Devastated',
  'Disappointed',
  'Discouraged',
  'Disgraced',
  'Disheartened',
  'Dismal',
  'Distant',
  'Distraught',
  'Distressed',
  'Abused',
  'Aggravated',
  'Agitated',
  'Anguished',
  'Annoyed',
  'Betrayed',
  'Cheated',
  'Coerced',
  'Controlled',
  'Deceived',
  'Disgusted',
  'Dominated',
  'Enraged',
  'Exploited',
  'Frustrated',
  'Furious',
  'Harassed',
  'Hateful',
  'Hostile',
  'Incensed',
  'Afraid',
  'Alarmed',
  'Anxious',
  'Appalled',
  'Apprehensive',
  'Awed',
  'Concerned',
  'Defensive',
  'Desperate',
  'Doubtful',
  'Fearful',
  'Frantic',
  'Full of dread',
  'Guarded',
  'Horrified',
  'Insecure',
  'Intimidated',
  'Nervous',
  'Overwhelmed',
  'Panicky',
  'Petrified',
  'Reluctant',
  'Shaken',
  'Ambivalent',
  'Awkward',
  'Baffled',
  'Bewildered',
  'Bothered',
  'Constricted',
  'Directionless',
  'Disorganized',
  'Distracted',
  'Doubtful',
  'Flustered',
  'Foggy',
  'Hesitant',
  'Misunderstood',
  'Perplexed',
  'Puzzled',
  'Stagnant',
  'Torn',
  'Trapped',
  'Troubled',
  'Uncertain',
  'Undecided',
  'Jubilant',
  'Grievous',
  'Irritated',
  'Shocked',
  'Unsettled',
  'Justified',
  'Helpless',
  'Mad',
  'Shy',
  'Unsure',
  'Loved',
  'Hopeless',
  'Offended',
  'Skeptical',
  'Marvelous',
  'Inadequate',
  'Outraged',
  'Startled',
  'Optimistic',
  'Humbled',
  'Patronized',
  'Stunned',
  'Peaceful',
  'Isolated',
  'Peeved',
  'Suspicious',
  'Pleased',
  'Islanded',
  'Perturbed',
  'Swamped',
  'Proud',
  'Lonely',
  'Pissed Off',
  'Tense',
  'Relaxed',
  'Miserable',
  'Provoked',
  'Terrified',
  'Relieved',
  'Mournful',
  'Rebellious',
  'Threatened',
  'Resolved',
  'Neglected',
  'Repulsed',
  'Timid',
  'Respected',
  'Pitiful',
  'Resentful',
  'Tormented',
  'Satisfied',
  'Regretful',
  'Ridiculed',
  'Uneasy',
  'Terrific',
  'Rejected',
  'Sabotaged',
  'Unsure',
  'Thrilled',
  'Resigned',
  'Seething',
  'Vulnerable',
  'Tranquil',
  'Sorrowful',
  'Smothered',
  'Valued',
  'Terrible',
  'Spiteful',
  'Unappreciated',
  'Stifled',
  'Uncared for',
  'Strangled',
  'Unloved',
  'Throttled',
  'Unwanted',
  'Uptight',
  'Upset',
  'Used',
  'Worthless',
  'Vengeful',
  'Wounded',
  'Vindictive',
]);

export const FALSE_STATUSES = Array.from(falseStatusSet);

// Date commands cause I hate this

export const isBeforeDate = (date: Date) => {
  return moment().isBefore(moment(date, 'YYYY-MM-DD'));
};

export const isAfterDate = (date: Date) => {
  return moment().isAfter(moment(date, 'YYYY-MM-DD'));
};
