export const POSITIVE_STATUS = [
  'Assured',
  'Cheerful',
  'Confident',
  'Content',
  'Delighted',
  'Determined',
  'Elated',
  'Encouraged',
  'Energized',
  'Fortunate',
  'Hopeful',
  'Joyful',
  'Jubilant',
  'Justified',
  'Pleased',
  'Loved',
  'Marvelous',
  'Optimistic',
  'Humbled',
  'Peaceful',
  'Proud',
  'Relaxed',
  'Thrilled',
  'Terrific',
  'Relieved',
  'Resolved',
];

export const NEUTRAL_STATUS = [
  'Admired',
  'Alive',
  'Appreciated',
  'Ecstatic',
  'Enthusiastic',
  'Excited',
  'Exuberant',
  'Flattered',
  'Fulfilled',
  'Glad',
  'Good',
  'Grateful',
  'Gratified',
  'Defensive',
  'Guarded',
  'Ambivalent',
  'Awkward',
  'Baffled',
  'Bewildered',
  'Mad',
  'Tranquil',
  'Disorganized',
  'Distracted',
  'Shy',
  'Valued',
  'Satisfied',
  'Respected',
];

export const NEGATIVE_STATUS = [
  'Alienated',
  'Ashamed',
  'Burdened',
  'Condemned',
  'Crushed',
  'Defeated',
  'Dejected',
  'Demoralized',
  'Depressed',
  'Deserted',
  'Despised',
  'Devastated',
  'Disappointed',
  'Discouraged',
  'Disgraced',
  'Disheartened',
  'Dismal',
  'Distant',
  'Distraught',
  'Distressed',
  'Abused',
  'Aggravated',
  'Agitated',
  'Anguished',
  'Annoyed',
  'Betrayed',
  'Cheated',
  'Coerced',
  'Controlled',
  'Deceived',
  'Disgusted',
  'Dominated',
  'Enraged',
  'Exploited',
  'Frustrated',
  'Furious',
  'Harassed',
  'Hateful',
  'Hostile',
  'Incensed',
  'Afraid',
  'Alarmed',
  'Anxious',
  'Appalled',
  'Apprehensive',
  'Awed',
  'Concerned',
  'Desperate',
  'Doubtful',
  'Fearful',
  'Frantic',
  'Full of dread',
  'Horrified',
  'Insecure',
  'Intimidated',
  'Nervous',
  'Overwhelmed',
  'Panicky',
  'Petrified',
  'Reluctant',
  'Shaken',
  'Bothered',
  'Constricted',
  'Directionless',
  'Doubtful',
  'Foggy',
  'Hesitant',
  'Stagnant',
  'Torn',
  'Trapped',
  'Troubled',
  'Grievous',
  'Irritated',
  'Shocked',
  'Unsettled',
  'Helpless',
  'Terrible',
  'Spiteful',
  'Unappreciated',
  'Stifled',
  'Uncared for',
  'Strangled',
  'Unloved',
  'Throttled',
  'Unwanted',
  'Uptight',
  'Upset',
  'Used',
  'Worthless',
  'Vengeful',
  'Wounded',
  'Vindictive',
  'Flustered',
  'Misunderstood',
  'Perplexed',
  'Puzzled',
  'Uncertain',
  'Undecided',
  'Unsure',
  'Hopeless',
  'Offended',
  'Skeptical',
  'Inadequate',
  'Outraged',
  'Startled',
  'Isolated',
  'Patronized',
  'Stunned',
  'Peeved',
  'Suspicious',
  'Islanded',
  'Perturbed',
  'Swamped',
  'Lonely',
  'Pissed Off',
  'Tense',
  'Miserable',
  'Provoked',
  'Terrified',
  'Mournful',
  'Rebellious',
  'Threatened',
  'Neglected',
  'Repulsed',
  'Timid',
  'Pitiful',
  'Resentful',
  'Tormented',
  'Regretful',
  'Ridiculed',
  'Uneasy',
  'Rejected',
  'Sabotaged',
  'Unsure',
  'Resigned',
  'Seething',
  'Vulnerable',
  'Sorrowful',
  'Smothered',
];

export const ALL_STATUSES = [
  ...POSITIVE_STATUS,
  ...NEUTRAL_STATUS,
  ...NEGATIVE_STATUS,
];

export function getRandomStatus() {
  return ALL_STATUSES[Math.floor(Math.random() * ALL_STATUSES.length)];
}

export function determineStatusType(
  status: string,
): 'positive' | 'neutral' | 'negative' {
  if (POSITIVE_STATUS.includes(status)) {
    return 'positive';
  }

  if (NEUTRAL_STATUS.includes(status)) {
    return 'neutral';
  }

  if (NEGATIVE_STATUS.includes(status)) {
    return 'negative';
  }

  return 'neutral';
}
